name: Build redacted varchar array transformer WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Add WASM target
        run: rustup target add wasm32-wasip1

      - name: Build
        run: cargo build --release --target wasm32-wasip1

      - name: Rename WASM file
        run: |
          mkdir -p release
          cp target/wasm32-wasip1/release/*.wasm release/redacted-varchar-array-transformer.wasm

      - name: Upload WASM as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: redacted-varchar-array-transformer
          path: release/redacted-varchar-array-transformer.wasm

#      - name: Create Release
#        if: github.even_name == 'push' && github.ref == 'refs/heads/main'
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: release-${{ github.run_number }}
#          release_name: Release ${{ github.run_number }}
#          draft: false
#          prerelease: false
#
#      - name: Upload release asset
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: release/redacted-varchar-array-transformer.wasm
#          asset_name: redacted-varchar-array-transformer.wasm
#          asset_content_type: application/wasm

      - name: Create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: release/redacted-varchar-array-transformer.wasm
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
